apiVersion: v1
kind: Service
metadata:
  name: p4-service
spec:
  type: ClusterIP
  selector:
    app: p4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p4
  template:
    metadata:
      labels:
        app: p4
    spec:
      containers:
        - name: p4
          image: yaseminozer/p4:latest
          ports:
            - containerPort: 8080